### ISSUE TITLE
host home mapping

### ISSUE THREAD

**Issue by senges** [senges/kitt#9]
Would be great to properly handle host home mapping inside container.

A quick hack to do so is :

```toml
[workspace]
user = "john"

[[workspace.volumes]]
host = "$HOME"
bind = "/home/john/host"
mode = "ro"
```

Follow-up question : where should it be mapped to inside container ? `/home/$USER/host` ?
